### ISSUE TITLE
How to circumvent: "{primaryKey} substitution not allowed ... "

### ISSUE THREAD

**Issue by bakroistvan** [FriendsOfCake/cakephp-upload#456]
How can I circumvent the "{primaryKey} substitution not allowed for new entities" error, when I configure the
    'path' => 'webroot{DS}files{DS}{model}{DS}{field}{DS}{primaryKey}{DS}'

There is a test.pdf file already uploaded. If I create a new entity, with the same filename it will overwrite the older.

**Comment by davidyell** [comment]
Think about it for a second. If you are creating a new entity and it's primary key is set by the database, as is most use-cases MySQL auto-increment or UUID, how will you know the primary key unless you insert the record?

**Comment by saeideng** [comment]
you can save your file in 2 step

**Comment by bakroistvan** [comment]
@davidyell Yes you are right.

@saeideng As I see things that's the way. I just started to use Cake3. The older version of this plugin is capable to save to a location containing the {primaryKey}.
It is doing definitely in a two or more step, but I just missed that feature. I think it is a must. What are your opinions?

**Comment by josegonzalez** [comment]
Hi! I'm the original author of both versions of the plugin (Cake2 and Cake3).

I removed support for `primaryKey` on entity create as it would indeed require a second update call to the database. Since files are processed *before* the entity is persisted to your datastore, this means that you might end up with dangling files on disk if the second `update` call failed. Furthermore, it would require more logic around entity property handling in an `afterSave` callback, and I didn't want to deal with the complexity.

My suggestion is that you do not use a `primaryKey`. If you need to support a specific field from your entity, you can use the new `{field-value:FIELD_NAME}` support. Add a new column to your entity called `unique_id` and populate it on entity creation. That way you can reference some persistent data on the record but also not tie yourself to a potentially breaking update call.

**Comment by saeideng** [comment]
> this means that you might end up with dangling files on disk if the second update call failed.

i personally ,i first save other field(s) ,and update the image field in second sql
by this way 
no files locate in disc if update fail
