### ISSUE TITLE
Test Fixtures have type `upload.file` for upload field.

### ISSUE THREAD

**Issue by tbelknapsgs** [FriendsOfCake/cakephp-upload#574]
I'm assuming this is a pretty simple bug. 
Version: 5.0.1
Cake: 4.1

Generating a new fixture for a table that has an uploadable file field. The output fixture marks the field type as "upload.file" rather than varchar.

**Comment by davidyell** [comment]
This is because it reads the schema for the table class, which stipulates that column type so the behaviour can process the file.

You'll need to manually change your fixture. There was some discussion about the root issue , but I can't find it now, the upshot was that the data type class should implement the base type of string.

Perhaps that needs to happen in the plugin? Either through `class FileType extends StringType`

**Comment by tbelknapsgs** [comment]
Thank you, David. This makes sense, just wasn't sure if this was the expected behavior, or not. Closing ticket.

**Comment by AdrianHL** [comment]
I found this issue happening when running filtered tests. The solution we found is to load the plugin in the test class so that the application was bootstrapped as expected as described in https://book.cakephp.org/4/en/development/testing.html#integration-testing-psr-7-middleware
PS. The app is on CakePHP 4.2, PHP 8.1 and PHPUnit 9.5.

**Comment by RichardPiel** [comment]
I got same error but i don't use fixtures but migrations to initialize test database.

Do you have solution to avoid this behavior ? 

Thanks

**Comment by angelxmoreno** [comment]
I encountered a similar issue, and initially thought it was related to my fixture setup. However, the third edit by RichardPiel was the solution that resolved it for me. Additionally, I ensured that the Josegonzalez/Upload plugin was loaded in my tests by adding the setUp() method in the ApplicationTest class:

```php
protected function setUp(): void {
    parent::setUp();
    $this->loadPlugins(['Josegonzalez/Upload']);
}
```
